spring:
  application:
    name: client
  profiles: client1
server:
  port: 50121
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8762/eureka,http://192.168.99.100:8763/eureka

---
spring:
  application:
      name: client
  profiles: client2
server:
  port: 50122
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka,http://192.168.99.100:8763/eureka

---
spring:
  application:
      name: client
  profiles: client3
server:
  port: 50123
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/,http://192.168.99.100:8762/eureka/