spring:
  application:
    name: client
  profiles: client1
server:
  port: 50121
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
---
spring:
  application:
      name: client
  profiles: client2
server:
  port: 50122
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  application:
      name: client
  profiles: client3
server:
  port: 50123
eureka:
  instance:
    hostname: client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
