spring:
  application:
      name: eureka-server
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka

---
spring:
  application:
        name: eureka-server
  profiles: peer2
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka

---
spring:
  application:
          name: eureka-server
  profiles: peer3
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/