spring:
  application:
    name: client
  profiles: client1
server:
  port: 0
eureka:
  instance:
     instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ipAddress}:${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  application:
      name: client
  profiles: client2
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  application:
      name: client
  profiles: client3
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
