spring:
  application:
      name: openAPI
server:
  port: 63795
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: false
---


spring:
  application:
      name: openAPI
  profiles: openAPI1
server:
  port: 63793
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  application:
      name: openAPI
  profiles: openAPI2
server:
  port: 63794
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

